pipeline {
  agent { label 'docker' } 
  environment {
    imagetag = GIT_COMMIT.take(7)
  }
  stages{
    stage("build"){
      tools{
        maven 'maven 3.6.1'  
      }
      when{
        changeset "**/vote/**"
      }
      steps{
        container('jnlp'){
          sh 'cd vote; mvn compile;'
        }
      }
    }
    stage("test"){
      tools{
        maven 'maven 3.6.1'  
      }
      when{
        changeset "**/vote/**"
      }
      steps{
        container('jnlp'){
          sh 'cd vote; mvn clean test;'
        }
      }
    }
    stage("packaging"){
      tools{
        maven 'maven 3.6.1'  
      }
      when{
        changeset "**/vote/**"
      }
      steps{
        container('jnlp'){
          sh 'cd vote; mvn package -DskipTests'
          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
      }
    }
    stage("build-and-push-image"){
      when{
        changeset "**/vote/**"
      }
      steps{
        container('kaniko'){
          sh 'ls -lah; env;'
          sh 'cd vote; ls -lah; /kaniko/executor --context `pwd` --verbosity debug --destination harbor5.btech.id/library/vote:${imagetag}'
        }
      }
    }


    stage("deploy-to-prod"){
      when{
        changeset "**/vote/**"
      }
      steps{
        container('jnlp'){
          sshagent(credentials: ['ssh-private-key-lb']) {
            sh '''
                echo $imagetag;
                [ -d ~/.ssh ] || mkdir ~/.ssh && chmod 0700 ~/.ssh
                ssh-keyscan -t rsa,dsa 10.99.99.11 >> ~/.ssh/known_hosts
                ssh root@10.99.99.11 ls -lah /root/deploy/vote
                ssh root@10.99.99.11 "echo ${imagetag}"
                ssh root@10.99.98.11 "cd /root/deploy/vote; helm upgrade vote . --set image.tag=${imagetag} -n default"
            '''
          }
        }
      }       
    }
  }
  post{
    always{
      echo 'Pipeline Complete'
    }
  }
}
